name: Docs Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest # Install and cache required apt packages
      with:
        packages: graphviz doxygen
    - name: Build Docs
      run: |
        set -e
        cd doc
        doxygen doxy.config
