name: Build project and run unit tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest # Install and cache required apt packages
      with:
        packages: build-essential cmake
    - name: Build and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make test
